services:
  db:
    image: postgres:16
    container_name: kcell_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kcell_store
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: kcell_store_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db